site_name: DevStudio
site_url: https://devstudio.example.com
nav:
  - Home: index.md
  - About: about.md
  - Templates:
      - Websites: websites.md
      - Others: others.md
  - API: api.md
  - FAQ: faq.md
  - Contact: contact.md
theme:
  name: material
plugins:
  - search
  - mkdocs-git-revision-date-localized-plugin
